### ISSUE TITLE
Bug: off by 1 when row > col

### ISSUE THREAD

**Issue by kozr** [Archiving/parallel-engine#27]
Issue: clicking on entities are off by 1 in terms of col when row > col

How to reproduce: Place an entity on a tile where row > col e.g. (row, col). Now you'd have to click (row, col + 1) to select the entity.

**Comment by ziqianma** [comment]
A line in tilemap.h inside screenToIso() was causing a problem when the x was negative (row > col). The line incremented the row by 1 whenever the row was larger than the col for a mouse offset (I'm not sure if this will cause any other problems within the project, since I did not add it). Without that line, clicking on the entity is accurate.
